### ISSUE TITLE
Incomplete example in the documentation

### ISSUE THREAD

**Issue by dabide** [anybox/buttervolume#15]
The documentation has the following example:

```
docker run --privileged -v /var/lib/docker/volumes:/var/lib/docker/volumes -v /run/docker/plugins:/run/docker/plugins anybox/buttervolume
```

However, running ` docker exec buttervolume buttervolume snapshot some_volume` exits with error code 1, as `/var/lib/docker/snapshots` isnt a btrfs volume.

The following works:
```
docker run --privileged \
-v /var/lib/docker/volumes:/var/lib/docker/volumes \
-v /var/lib/docker/snapshots:/var/lib/docker/snapshots \
-v /run/docker/plugins:/run/docker/plugins \
anybox/buttervolume
```

Should `/var/lib/docker/received` also be added the same way?

**Comment by ccomb** [comment]
Thanks for the issue and sorry for the delay.
We're about to release buttervolume 2.0 which only has a /var/lib/buttervolume. It has been updated in the doc.
