### ISSUE TITLE
Docker creates local volumes if buttervolume container hasn't been started yet

### ISSUE THREAD

**Issue by dabide** [anybox/buttervolume#16]
During a reboot or a restart of the Docker daemon, the buttervolume container isn't always the first to be started.

That means that Docker will create local storage volumes for containers that are started before buttervolume is up and running.

Is there any way to avoid this?

**Comment by petrus-v** [comment]
Thanks for reporting,

We are aware about this issue. Sorry, we have managed this issue in a private bug tracker. At the time writing, we are not that much impacted by this issue as long we are moving away all btrfs volumes before plan reboot.

Next release will fix that, [this recent commit](https://github.com/anybox/buttervolume/commit/32d4bc3f59741f7f4bf381975a8b9e70b486f128) in the master branch change path from ``/var/lib/docker/volumes`` to ``/var/lib/docker/buttervolumes``. As suggested in the [docker volume documentation](https://docs.docker.com/engine/extend/plugins_volume/):

> Note: Volume plugins should not write data to the ``/var/lib/docker/`` directory,
> including ``/var/lib/docker/volumes``. The ``/var/lib/docker/`` directory is reserved for Docker.

So we may change again this path and expect to make this path settable for a smoothie transition between v1.x and v2.x.

I'm letting this issue open until next release.

Regards,

**Comment by ccomb** [comment]
Thanks,
This is fixed in buttervolume 2.0, but all the snapshots and volumes must be migrated to the new location, which is not always easy.
I've added a simple migration process, but all depends on how you set up your subvolumes.
