### ISSUE TITLE
Ambiguity in docs about config.ini

### ISSUE THREAD

**Issue by kaotika** [anybox/buttervolume#19]
The docs says the configuration and schedules reside in `/etc/buttervolume/schedule.csv` and `/etc/buttervolume/config.ini`. As far as I find out this is just the path inside the plugin container, not on the host machine. Is this correct? 
I think its better to tell the user to put the files inside `/var/lib/buttervolume/config`.

**Comment by petrus-v** [comment]
Hi,

Thanks for reporting here, you are right feel free to create a PR to update to improve the documentation.

regards

**Comment by ccomb** [comment]
Hi, thanks for your feedback! You're right actually it's simpler to put the files in /var/lib/buttervolume/config, it's a late change for version 3.0 and may the doc was not updated.  I'm pushing a clarification now. Feel free to reopen if it's not clear enough.
