### ISSUE TITLE
Change SSH port

### ISSUE THREAD

**Issue by bananer** [anybox/buttervolume#40]
Is it possible to change the port used for SSH form the default 1122?

[This file](https://github.com/anybox/buttervolume/blob/master/docker/README.rst) seems to indicate setting the environment variable `SSH_PORT` should work, but I tried:

    docker plugin set anybox/buttervolume SSH_PORT=3181

which gives me:

    Error response from daemon: setting "SSH_PORT" not found in the plugin configuration

**Comment by petrus-v** [comment]
Indeed the env variable is used in the [entrypoint](https://github.com/anybox/buttervolume/blob/master/docker/entrypoint.sh#L3) of the plugin...

But is not declared in the docker [plugin config manifest](https://github.com/anybox/buttervolume/blob/master/docker/config.json)
(cf [Plugin configuration](https://docs.docker.com/engine/extend/config/)).

[docker plugin set](https://docs.docker.com/engine/reference/commandline/plugin_set) 

If I remember we use this variable on test environment without plugin
