### ISSUE TITLE
Can I use native btrfs commands instead of the buttervolume cli ?

### ISSUE THREAD

**Issue by LelouBil** [anybox/buttervolume#49]
I plan to replace my existing rollback after deployment system to buttervolume and btrfs snapshots, for now I was tar-ing my volumes, but this takes a while.

This is automated in an ansible playbook, and I have two (small) issues here:
1. Using the runc execution is cumbersome in ansible
2. I would like to manage the location and name of snapshots created by the playbook (but not by snapshots created outside, so I won't change the path in the config)

So can I just use btrfs subvolume snapshot on a volume directory ? Does buttervolume have any state that could get out of sync if I use btrfs manually on its folders/volumes ?

**Comment by ccomb** [comment]
Hi, thanks for trying to use Butervolume!  I believe it has no state, apart from the schedule of the periodic snapshots which is stored in /etc/buttervolume/schedule.csv inside the plugin.  The only kind of statish thing might be the name of the snapshots, which are based on a [volume_name@timestamp](https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L305C19-L305C32) pattern, and which are used to sort them and find the latest and the corresponding volume.  Anyway you can try what you need and keep me in touch of any difficulties you encounter?

**Comment by LelouBil** [comment]
Okay, that's great, I started to use the btrfs commands in the playbook and got no issues so far. I don't need the snapshots from the playbook to appear when using the buttervolume cli, so the volume name pattern is not an issue for me.
