### ISSUE TITLE
parsing date from snapshots name

### ISSUE THREAD

**Issue by petrus-v** [anybox/buttervolume#5]
At least while purging snapshots we are reading date that were generated by [datetime.isoformat](https://docs.python.org/3.5/library/datetime.html?highlight=datetime#datetime.datetime.isoformat) if we are unlucky we get the time with 0 microsecond, in that case the format is a bit different:
```python
(Pdb) datetime(2017,4,3,21,24,0,101).isoformat()
'2017-04-03T21:24:00.000101'
(Pdb) datetime(2017,4,3,21,24,0,0).isoformat()
'2017-04-03T21:24:00'
```
So while parsing that string we can get a *ValueError* exception:
```python
(Pdb) datetime.strptime("buttervolume-test-eaf7bb4c65ed4f2ea9c30ef6c33f0f00@2017-04-03T21:24:00@123".split('@')[1], "%Y-%m-%dT%H:%M:%S.%f")
*** ValueError: time data '2017-04-03T21:24:00' does not match format '%Y-%m-%dT%H:%M:%S.%f'
(Pdb) datetime.strptime("buttervolume-test-eaf7bb4c65ed4f2ea9c30ef6c33f0f00@2017-04-03T21:24:00.12@123".split('@')[1], "%Y-%m-%dT%H:%M:%S.%f")
datetime.datetime(2017, 4, 3, 21, 24, 0, 120000)

```

**Comment by ccomb** [comment]
thx for the report, I've replaced the isoformat with a strftime
