### ISSUE TITLE
disable debug log by default

### ISSUE THREAD

**Issue by missedone** [anybox/buttervolume#6]
hi,
I ran buttervolume from the pre-baked docker image:
```
root@ca4c855d6f0d:/# buttervolume snapshots
DEBUG:requests.packages.urllib3.connectionpool:http://localhost:None "POST /VolumeDriver.Snapshot.List HTTP/1.1" 200 28
```

1) `http://localhost:None`, the port "None" looks confusing, though the result is good
2) can we disable the DEBUG log by default?
thx

**Comment by petrus-v** [comment]
Hi,

Thanks for report, yes good Idea, do you mind to do the PR for that?

regards

**Comment by missedone** [comment]
sorry, i'm not quite family with the buttervolume code structure, i tried add line `logging.getLogger('requests.packages.urllib3.connectionpool').setLevel(logging.INFO)` to cli.py, but looks like it does not work.

**Comment by petrus-v** [comment]
Oops, reading the code, it's looks like level info is an hard coded value on each files:

* https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L11
* https://github.com/anybox/buttervolume/blob/master/buttervolume/cli.py#L18
* ...

We have to change that behavior and be able to set logging config from parameters.

**Comment by marcelo-ochoa** [comment]
I changed LogLevel to ERROR in both files. See code at #11 #9

**Comment by petrus-v** [comment]
@marcelo-ochoa,

Yes I've seen that, I think at the time this issue was created it was ``DEBUG```level but anyway this should be settable somehow!

**Comment by ccomb** [comment]
In buttervolume 2.0 the log level is configurable through an environment variable or an /etc/buttervolume/config.ini file.
