### ISSUE TITLE
use snapshot when mount

### ISSUE THREAD

**Issue by missedone** [anybox/buttervolume#7]
hi, 
in my use case, i'd like to setup db volume container for QA testing pursue, use the feature of btrfs that each container use the snapshot the volume so that any testing data will be discard once QA finish the test (clean the containers), also the testing data in each container won't pollute the base data in the volume.
so the workflow is such as below:
1. create base data volume
2. create container use that base volume
3. create snapshot of the volume before run the container
4. [perform routine test as QA team do...]
5. remove the container
6. remove the snapshot that container binds.

for now, i was hoping buttervolume can create the snapshot when Mount and remove it when Unmount in automatic manner, however looks like buttervolume does not support this.

i'm thinking to suppose this by introducing a env or conf property, (e.g. btrfs_driver_snapshot_on_mount=true/false), if it's true, then buttervolume will create a snapshot and track it somewhere so that the correct snapshot will be removed when unmount.
what do you think?

see also: https://docs.docker.com/engine/extend/plugins_volume/#volumedrivermount

**Comment by petrus-v** [comment]
Hi,

Thanks for filling this issue, interesting workflow!

Today we are using this tool with a custom consul handler to manage snapshots. 

So you can see in the code at [Volume driver mount time](https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L48) we are only checking copy on write is enable or not and on [Volume driver create](https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L32) time checking if the volume exists all other behavior are expected to be done through the command line buttervolume client or using new api entry points, likes (this is not an exhaustive list):

* [/VolumeDriver.Volume.Sync](https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L32): rsync the same volume name from another host
* [/VolumeDriver.Snapshot.Send](https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L151): send a snapshot to an other host
* [/VolumeDriver.Snapshot](https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L20): Create a snapshot of a given volume
* [/VolumeDriver.Snapshot.Restore](https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L282): Restore a snapshot as volume

So I guess what you will need to do is:

- On each worker host, run a container with this code that is used as Docker Volume Driver
- Your QA will needs to use buttervolume cli or call the deamon directly to manage snapshots and volumes for you, Assuming you'll use the cli (as for us with our consul handler) you can install this python library in an other container or on the host machine as long /run/docker/plugins is accessible.


So let's say:

 * we have only one host where you are working on and running all your tests.
 * you already configure a container with buttervolume called ``plugin_btrfs``

Then (following examples haven't been tested):

- First create a btrfs volume that you want to use in your tests:
```bash
docker volume create -d btrfs base_test
```
- Do what ever you want as usual to fill base_test volume
```bash
docker run -v base_test:/tmp/test alpine touch /tmp/test/file1
```
- at this point a btrfs subvolume should be exists in ``/var/lib/docker/volumes/base_test``
```bash
docker volume ls
docker volume inspect base_test
```
> **Note**: you can directly use btrfs command from the host machine (ie btrfs subvolume snapshot ...)

- Once you are happy, create a snapshot with your test volumes
```bash
docker exec -it plugin_btrfs buttervolume snapshot base_test
```

- At that time you have a readonly snapshot available under something
  likes ``/var/lib/docker/snapshots/base_test@2017-06-09T09:22:13.437657``

- now you can remove your volume as usual the snapshot will stay in place:
```bash
docker volume rm base_test
```
- Then your bot before running test have to restore the snapshot before running the docker container
```bash
docker exec -it plugin_btrfs buttervolume restore base_test
```
> **Note**: once again you can install the python cli command line in an other container if it access to the ``/run/docker/plugins`` repository

- Finally you can create a snapshot or send it somewhere else or cleanup the test volume using docker command 


I guess missing feature would be to rename a volume while restoring a snapshot and maybe pull snapshot instead send it to an other host, If you create some PR we would be please to review and merge them.

Hop that helps!

**Comment by missedone** [comment]
thanks for sharing your workflow and answered some question in my mind:)

yes, our case is running on single node. and I'm trying to figure out a way to make the snapshot process transparent to the qa developers.
ideally, it will be very simple to docker build and run, which means, I think there will be build time and runtime operations, at build time it's just build the base subvolume just like (alike docker images), and the snapshots created from that base subvolume (alike docker containers).
and also i'm trying to simply the workflow.
will need to think more.
