### ISSUE TITLE
[Question] how does it compare to local driver with -o type=btrfs option ?

### ISSUE THREAD

**Issue by docteurklein** [anybox/buttervolume#8]
I'm curious. Does this volume driver creates block devices on the fly and all?

**Comment by petrus-v** [comment]
Hi,

Thanks for your interest.

This driver assume you already have a btrfs partition so you can create BTRFS sub-volumes in the following directories:
* /var/lib/docker/volumes
* /var/lib/docker/snapshots
* /var/lib/docker/received

You can read how we [setup developer environment](https://github.com/anybox/buttervolume#test) to give you an idea of requirements.

In the driver code you can see here what's happen while [creating a new volume](https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L42): 
```python
@route('/VolumeDriver.Create', ['POST'])
def volume_create():
    [...]
    btrfs.Subvolume(volpath).create()
    [...]
```

which call [btrf wraper code](https://github.com/anybox/buttervolume/blob/master/buttervolume/btrfs.py#L39):
```python
    def create(self, cow=False):
        out = run('btrfs subvolume create "{}"'.format(self.path))
        if not cow:
            run('chattr +C "{}"'.format(self.path))
        return out
```

hope that helps!

**Comment by docteurklein** [comment]
thanks!
