### ISSUE TITLE
[Enhancement] Multiple snapshots as new mounts (clone volume)

### ISSUE THREAD

**Issue by marcelo-ochoa** [anybox/buttervolume#9]
Is it possible to implement snapshot create as new volume (cloning)?
My use case is to provide a base mount point with an immutable installation of the software and creates multiples copies of that base image as snapshot for new mount point.
Now I doing this:
```
$ docker run --shm-size=1g --name apex --hostname apex -p 1521:1521 -p 8080:8080 --volume-driver=btrfs -v apex-5.1.4:/u01/app/oracle/oradata oracle/database:11.2.0.2-xe
$ docker stop apex
$ docker exec -ti plugin_btrfs buttervolume snapshot apex-5.1.4
$ docker exec -ti plugin_btrfs buttervolume restore "apex-5.1.4@2017-09-14T20:18:29.012797" apex-5.1.4-app1
$ docker exec -ti plugin_btrfs buttervolume restore "apex-5.1.4@2017-09-14T20:18:29.012797" apex-5.1.4-app2
$ docker exec -ti plugin_btrfs buttervolume restore "apex-5.1.4@2017-09-14T20:18:29.012797" apex-5.1.4-app3
$ docker run --shm-size=1g --name apex-app1 --hostname apex -p 15121:1521 -p 8081:8080 --volume-driver=btrfs -v apex-5.1.4-app1:/u01/app/oracle/oradata oracle/database:11.2.0.2-xe
$ docker run --shm-size=1g --name apex-app2 --hostname apex -p 15221:1521 -p 8082:8080 --volume-driver=btrfs -v apex-5.1.4-app2:/u01/app/oracle/oradata oracle/database:11.2.0.2-xe
$ docker run --shm-size=1g --name apex-app3 --hostname apex -p 15321:1521 -p 8083:8080 --volume-driver=btrfs -v apex-5.1.4-app3:/u01/app/oracle/oradata oracle/database:11.2.0.2-xe
```
I would like to do something like this:
```
$ docker run --shm-size=1g --name apex --hostname apex -p 1521:1521 -p 8080:8080 --volume-driver=btrfs -v apex-5.1.4:/u01/app/oracle/oradata oracle/database:11.2.0.2-xe
$ docker stop apex
$ docker exec -ti plugin_btrfs buttervolume clone apex-5.1.4 apex-5.1.4-app1
$ docker exec -ti plugin_btrfs buttervolume clone apex-5.1.4 apex-5.1.4-app2
$ docker exec -ti plugin_btrfs buttervolume clone apex-5.1.4 apex-5.1.4-app3
$ docker run --shm-size=1g --name apex-app1 --hostname apex -p 15121:1521 -p 8081:8080 --volume-driver=btrfs -v apex-5.1.4-app1:/u01/app/oracle/oradata oracle/database:11.2.0.2-xe
$ docker run --shm-size=1g --name apex-app2 --hostname apex -p 15221:1521 -p 8082:8080 --volume-driver=btrfs -v apex-5.1.4-app2:/u01/app/oracle/oradata oracle/database:11.2.0.2-xe
$ docker run --shm-size=1g --name apex-app3 --hostname apex -p 15321:1521 -p 8083:8080 --volume-driver=btrfs -v apex-5.1.4-app3:/u01/app/oracle/oradata oracle/database:11.2.0.2-xe
```
this enhancement will be great to prepare environment for training purpose.
Many thanks, in advance. Marcelo.

**Comment by petrus-v** [comment]
Hi @marcelo-ochoa,

Thanks for reporting here! we haven't plan to implement this feature right now but we would be please to review and merge your contribution if you create a PR.

Please let us know what you intent to do?

regards

**Comment by marcelo-ochoa** [comment]
Well I am not a Phyton developer, but I'll try to do my best.
Best regards, Marcelo.

**Comment by marcelo-ochoa** [comment]
Well using **_btrfs_** command line I got my desired functionality by simple executing:
`# btrfs subvolume snapshot /var/lib/docker/volumes/apex-5.1.4 /var/lib/docker/volumes/apex-5.1.4-app4`
after that running **_docker volume_** command shows a correct output :)
```
# docker volume ls
DRIVER              VOLUME NAME
local               480892f214a8514905e1112227a1f031a1d5527d7edbed56a7a380afe6577477
local               5742d0cd1d4a0833d18f0e542393a01930e7131f6e4dc757faa4e4b3dba88f67
local               7e633ed027cb1a3d1825559d0092ec21da6641fda21c530fe4e98ae38475b761
btrfs               apex-5.1.4
btrfs               apex-5.1.4-app1
btrfs               apex-5.1.4-app2
btrfs               apex-5.1.4-app3
btrfs               apex-5.1.4-app4
```
So we have the alternative of working with **_btrfs_** commands or adding a hook in **_cli.py_** and **_plugin.py_** to accept a command like:
`$ docker exec -ti plugin_btrfs buttervolume clone apex-5.1.4 apex-5.1.4-app4`
to run above **_btrfs_** command.
Best regards, Marcelo.

**Comment by petrus-v** [comment]
@marcelo-ochoa,

Yes that right, this will looks like [revert method](https://github.com/anybox/buttervolume/blob/master/buttervolume/plugin.py#L283) which call [btrf subvolume snapshot](https://github.com/anybox/buttervolume/blob/master/buttervolume/btrfs.py#L34) as you said.

Regards,

**Comment by marcelo-ochoa** [comment]
[clone.patch.txt](https://github.com/anybox/buttervolume/files/1310954/clone.patch.txt)
Here a patch for cli.py and plugin.py including clone functionality. Marcelo.

**Comment by petrus-v** [comment]
as long #11 was merged I close this issue!
